export enum ElementType {
  TEXT = 'text',
  IMAGE = 'image',
  TABLE = 'table',
  HYPERLINK = 'hyperlink',
  SUPERSCRIPT = 'superscript',
  SUBSCRIPT = 'subscript',
  SEPARATOR = 'separator',
  PAGE_BREAK = 'pageBreak',
  CONTROL = 'control',
  AREA = 'area',
  CHECKBOX = 'checkbox',
  RADIO = 'radio',
  LATEX = 'latex',
  TAB = 'tab',
  DATE = 'date',
  BLOCK = 'block',
  TITLE = 'title',
  LIST = 'list',
  PLACEHOLDER = 'placeholder',
  FOOTNOTE_MARK = 'footnoteMark',
  FOOTNOTE_CONTENT = 'footnoteContent',
  FOOTNOTE_SEPARATOR = 'footnoteSeparator',
  COLUMN_BREAK = 'columnBreak',
  REVISION_INSERT = 'revisionInsert',
  REVISION_DELETE = 'revisionDelete',
  SHAPE = 'shape'
}
