export { CommentComponent } from './comment/comment-component'
export type { DocxCommentMeta, CommentCallbacks } from './comment/comment-component'
export { RevisionComponent } from './comment/revision-component'
export type { RevisionCallbacks } from './comment/revision-component'
export type { CommentHost, GroupAnchor, GroupContext } from './comment/host'
