import {
  mdiContentSaveOutline,
  mdiPrinterOutline,
  mdiUndo,
  mdiRedo,
  mdiContentCut,
  mdiContentCopy,
  mdiContentPaste,
  mdiSelectAll,
  mdiDeleteOutline,
  mdiEyeOutline,
  mdiEyeOffOutline,
  mdiGrid,
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatUnderline,
  mdiFormatStrikethrough,
  mdiFormatAlignLeft,
  mdiFormatAlignCenter,
  mdiFormatAlignRight,
  mdiFormatClear,
  mdiTableRowPlusBefore,
  mdiTableRowPlusAfter,
  mdiTableColumnPlusBefore,
  mdiTableColumnPlusAfter,
  mdiTableMergeCells,
  mdiTableSplitCell,
  mdiTableRemove,
  mdiTableRow,
  mdiTableColumn,
  mdiSortAscending,
  mdiSortDescending,
  mdiHelpCircleOutline,
  mdiKeyboardOutline,
  mdiWrap,
  mdiFormatText,
  mdiFormatParagraph,
  mdiSnowflake,
  mdiCheckboxMarkedOutline,
  mdiCheckboxBlankOutline,
  mdiPlus,
  mdiMinus,
  mdiTableMinus,
  mdiLinkVariant,
  mdiMagnify,
  mdiMagnifyPlus,
  mdiMagnifyMinus,
  mdiFindReplace,
  mdiPrinter,
  mdiCommentPlusOutline,
  mdiCurrencyUsd,
  mdiPercent,
  mdiDecimalDecrease,
  mdiDecimalIncrease,
  mdiFormatVerticalAlignTop,
  mdiFormatVerticalAlignCenter,
  mdiFormatVerticalAlignBottom,
  mdiFormatTextRotationNone,
  mdiFormatTextRotationUp,
  mdiFormatTextRotationDown,
  mdiFormatTextRotationVertical,
  mdiFilterOutline,
  mdiImageOutline,
  mdiSigma,
  mdiFunctionVariant,
  mdiChevronDown,
  mdiFormatColorFill,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiFileExcelBox,
  mdiArrowExpandVertical,
  mdiArrowExpandHorizontal,
  mdiArrowCollapseVertical,
  mdiArrowCollapseHorizontal,
  mdiCheckCircleOutline,
  mdiCrop,
  mdiArrowRight,
  mdiCheck,
} from '@mdi/js'

const iconMap: Record<string, string> = {
  'content-save-outline': mdiContentSaveOutline,
  'printer-outline': mdiPrinterOutline,
  'undo': mdiUndo,
  'redo': mdiRedo,
  'content-cut': mdiContentCut,
  'content-copy': mdiContentCopy,
  'content-paste': mdiContentPaste,
  'select-all': mdiSelectAll,
  'delete-outline': mdiDeleteOutline,
  'eye-outline': mdiEyeOutline,
  'eye-off-outline': mdiEyeOffOutline,
  'grid': mdiGrid,
  'format-bold': mdiFormatBold,
  'format-italic': mdiFormatItalic,
  'format-underline': mdiFormatUnderline,
  'format-strikethrough': mdiFormatStrikethrough,
  'format-align-left': mdiFormatAlignLeft,
  'format-align-center': mdiFormatAlignCenter,
  'format-align-right': mdiFormatAlignRight,
  'format-clear': mdiFormatClear,
  'table-row-plus-before': mdiTableRowPlusBefore,
  'table-row-plus-after': mdiTableRowPlusAfter,
  'table-column-plus-before': mdiTableColumnPlusBefore,
  'table-column-plus-after': mdiTableColumnPlusAfter,
  'table-merge-cells': mdiTableMergeCells,
  'table-split-cell': mdiTableSplitCell,
  'table-remove': mdiTableRemove,
  'table-row': mdiTableRow,
  'table-column': mdiTableColumn,
  'table-row-remove': mdiTableRemove,
  'table-column-remove': mdiTableRemove,
  'table-minus': mdiTableMinus,
  'sort-ascending': mdiSortAscending,
  'sort-descending': mdiSortDescending,
  'help-circle-outline': mdiHelpCircleOutline,
  'keyboard-outline': mdiKeyboardOutline,
  'text-wrap': mdiWrap,
  'format-text': mdiFormatText,
  'format-paragraph': mdiFormatParagraph,
  'snowflake': mdiSnowflake,
  'checkbox-marked-outline': mdiCheckboxMarkedOutline,
  'checkbox-blank-outline': mdiCheckboxBlankOutline,
  'plus': mdiPlus,
  'minus': mdiMinus,
  'link-variant': mdiLinkVariant,
  'magnify': mdiMagnify,
  'magnify-plus': mdiMagnifyPlus,
  'magnify-minus': mdiMagnifyMinus,
  'find-replace': mdiFindReplace,
  'printer': mdiPrinter,
  'comment-plus-outline': mdiCommentPlusOutline,
  'currency-usd': mdiCurrencyUsd,
  'percent': mdiPercent,
  'decimal-decrease': mdiDecimalDecrease,
  'decimal-increase': mdiDecimalIncrease,
  'format-vertical-align-top': mdiFormatVerticalAlignTop,
  'format-vertical-align-center': mdiFormatVerticalAlignCenter,
  'format-vertical-align-bottom': mdiFormatVerticalAlignBottom,
  'format-text-rotation-none': mdiFormatTextRotationNone,
  'format-text-rotation-up': mdiFormatTextRotationUp,
  'format-text-rotation-down': mdiFormatTextRotationDown,
  'format-text-rotation-vertical': mdiFormatTextRotationVertical,
  'filter-outline': mdiFilterOutline,
  'image-outline': mdiImageOutline,
  'sigma': mdiSigma,
  'function-variant': mdiFunctionVariant,
  'chevron-down': mdiChevronDown,
  'format-color-fill': mdiFormatColorFill,
  'fullscreen': mdiFullscreen,
  'fullscreen-exit': mdiFullscreenExit,
  'file-excel-box': mdiFileExcelBox,
  'arrow-expand-vertical': mdiArrowExpandVertical,
  'arrow-expand-horizontal': mdiArrowExpandHorizontal,
  'arrow-fit-vertical': mdiArrowCollapseVertical,
  'arrow-fit-horizontal': mdiArrowCollapseHorizontal,
  'check-circle-outline': mdiCheckCircleOutline,
  'crop': mdiCrop,
  'arrow-right': mdiArrowRight,
  'check': mdiCheck,
}

export function resolveSheetIcon(name: string): string | undefined {
  if (!name) return undefined
  let key = name.trim()
  if (key.startsWith('mdi ')) key = key.slice(4)
  if (key.startsWith('mdi-')) key = key.slice(4)
  return iconMap[key]
}
