export default {
  chart: {
    dialog: { title: 'Insert Chart', settings: 'Settings', data: 'Data', selectType: 'Select Chart Type', preview: 'Chart Preview', config: 'Chart Settings', clear: 'Clear', cancel: 'Cancel', confirm: 'OK' },
    category: { bar: 'Column', line: 'Line', pie: 'Pie', scatter: 'Scatter', radar: 'Radar', mixed: 'Combo' },
    preview: { 'bar-basic': 'Basic Column', 'bar-stacked': 'Stacked Column', 'bar-horizontal': 'Horizontal Bar', 'line-basic': 'Basic Line', 'line-smooth': 'Smooth Line', 'line-stacked': 'Stacked Line', 'line-area': 'Stacked Area', 'line-step': 'Stepped Line', 'line-dashed': 'Dashed Line', 'pie-basic': 'Basic Pie', 'pie-doughnut': 'Doughnut', 'scatter-basic': 'Basic Scatter', 'radar-basic': 'Basic Radar', 'radar-filled': 'Filled Radar', 'mixed-line-bar': 'Line and Column' },
    config: { showTitle: 'Show Title', title: 'Title', titlePlaceholder: 'Enter chart title', titlePosition: 'Title Position', showLegend: 'Show Legend', legendPosition: 'Legend Position', xAxisLabel: 'X-Axis Title', xAxisPlaceholder: 'Enter X-axis title', yAxisLabel: 'Y-Axis Title', yAxisPlaceholder: 'Enter Y-axis title', showGrid: 'Show Gridlines', showDataLabel: 'Show Data Labels', colorScheme: 'Color Scheme' },
    position: { left: 'Left', center: 'Center', right: 'Right', top: 'Top', bottom: 'Bottom' },
    colorScheme: { default: 'Default', warm: 'Warm', cool: 'Cool', nature: 'Natural' },
    sample: { series: 'Series {index}', category: 'Category {index}' },
    noData: 'No data', data: 'Data'
  },
  view: {
    common: { cancel: 'Cancel', confirm: 'OK', none: 'None', leftAlign: 'Align Left', rightAlign: 'Align Right', center: 'Center', justify: 'Justify', distribute: 'Distributed', preview: 'Preview', color: 'Color', spacing: 'Spacing', points: 'pt' },
    paragraph: { format: 'Paragraph Formatting', body: 'Body Text', heading1: 'Heading 1', heading2: 'Heading 2', heading3: 'Heading 3', heading4: 'Heading 4', heading5: 'Heading 5', heading6: 'Heading 6', cut: 'Cut', copy: 'Copy', paste: 'Paste', fontSettings: 'Font...', advancedSettings: 'Advanced Paragraph Settings', link: 'Hyperlink', comment: 'Insert Comment' },
    hyperlink: { text: 'Display Text', address: 'Link Address', addressPlaceholder: 'Enter a full address (e.g. https://example.com)', textRequired: 'Please enter display text', addressRequired: 'Please enter a link address', addressInvalid: 'The link address must use http, https, mailto, tel, or ftp protocol', unsupported: 'Unable to insert hyperlink: the current selection is unsupported, contains revisions, or the document is in revision/read-only mode; the document was not modified' },
    table: { insert: 'Insert', insertLeft: 'Insert Left', insertRight: 'Insert Right', insertAbove: 'Insert Above', insertBelow: 'Insert Below', columnUnit: 'column(s)', rowUnit: 'row(s)', insertCell: 'Cell (E)...', splitCell: 'Split Cells', mergeCell: 'Merge Cells', delete: 'Delete', deleteRow: 'Delete Row', deleteColumn: 'Delete Column', deleteTable: 'Delete Table', selectAll: 'Select Entire Table', horizontalAlign: 'Horizontal Alignment', centerAlign: 'Center', verticalAlign: 'Vertical Alignment', alignTop: 'Align Top', alignMiddle: 'Align Middle', alignBottom: 'Align Bottom', background: 'Shading Color', repeatHeader: 'Repeat Header Row', properties: 'Table Properties', select: 'Select Table', addColumn: 'Add Column', addRow: 'Add Row' },
    font: { title: 'Font', characterSpacing: 'Character Spacing', cjkFont: 'Chinese Font', style: 'Font Style', regular: 'Regular', italic: 'Italic', bold: 'Bold', boldItalic: 'Bold Italic', size: 'Size', effects: 'Effects', strikethrough: 'Strikethrough', underline: 'Underline', superscript: 'Superscript', subscript: 'Subscript', doubleStrikethrough: 'Double Strikethrough', hidden: 'Hidden', previewText: 'Font preview text ABCabc 123', scale: 'Scale', standard: 'Normal', expanded: 'Expanded', condensed: 'Condensed', position: 'Position', raised: 'Raised', lowered: 'Lowered', spacingPreview: 'Character spacing preview ABCabc 123', unsupported: 'Spacing and position will be supported in a future release' },
    paragraphDialog: { title: 'Paragraph', indentSpacing: 'Indents and Spacing', linePageBreak: 'Line and Page Breaks', cjkLayout: 'Asian Typography', general: 'General', alignment: 'Alignment', outline: 'Outline Level', bodyText: 'Body Text', level1: 'Level 1', level2: 'Level 2', level3: 'Level 3', level4: 'Level 4', level5: 'Level 5', level6: 'Level 6', indent: 'Indentation', beforeText: 'Before text', afterText: 'After text', special: 'Special', firstLine: 'First line', hanging: 'Hanging', measure: 'By', cm: 'cm', adjustRightIndent: 'Automatically adjust right indent when document grid is defined', before: 'Before', after: 'After', lineSpacing: 'Line spacing', single: 'Single', oneHalf: '1.5 lines', double: 'Double', atLeast: 'At least', exact: 'Exactly', multiple: 'Multiple', setting: 'At', times: 'times', alignGrid: 'Snap to grid when document grid is defined', previewText: 'Paragraph preview text', pagination: 'Pagination', widow: 'Widow/Orphan control', keepNext: 'Keep with next', breakBefore: 'Page break before', lineBreak: 'Line breaks', noLineNumber: 'Suppress line numbers', noHyphen: 'Do not hyphenate', unsupported: 'This feature will be supported in a future release', cjkWrap: 'Use Chinese line-breaking rules', punctuationOverflow: 'Allow punctuation to extend beyond margins', wordBreak: 'Allow Latin text to break within words', compressPunctuation: 'Compress punctuation at the start of a line', cjkWesternSpacing: 'Automatically adjust spacing between Chinese and Latin text', cjkNumberSpacing: 'Automatically adjust spacing between Chinese and numbers', textAlignment: 'Text alignment', align: 'Alignment', auto: 'Automatic', baseline: 'Align to baseline' },
    tableDialog: { categories: 'Property Categories', table: 'Table', cell: 'Cell', presetHint: 'Presets replace the entire table border configuration. Unselected edges will be cleared.', border: 'Border', preset: 'Preset', unchanged: 'Keep Existing', allBorders: 'All Borders', outsideBorders: 'Outside Borders', noBorders: 'No Borders', insideBorders: 'Inside Borders', insideHorizontal: 'Inside Horizontal', insideVertical: 'Inside Vertical', topBorder: 'Top Border', bottomBorder: 'Bottom Border', leftBorder: 'Left Border', rightBorder: 'Right Border', borderPresets: 'Border Presets', all: 'All', outside: 'Outside', inside: 'Inside', colorFormatTitle: 'Enter a color in #RRGGBB format', colorFormatClearTitle: 'Enter a color in #RRGGBB format; leave blank to clear', borderColor: 'Border Color', cellColor: 'Cell Background', chooseColor: 'Choose {label} (current: {state})', innerWidth: 'Inner Border Width', outerWidth: 'Outer Border Width', innerWidthAria: 'Inner border width (pixels)', outerWidthAria: 'Outer border width (pixels)', colorHelp: 'Color format: #RRGGBB; leave blank to keep existing.', borderPreview: 'Border Preview', presetPreview: 'Border configuration preview; dashed lines show only the table bounds. Unspecified colors and widths stay unchanged.', unchangedPreview: 'No preset selected; borders stay unchanged. The preview does not represent mixed styles.', cellHint: 'These settings apply only to the current cell (the one right-clicked).', fill: 'Fill', noFill: 'No Fill', invalidColor: 'Invalid color format', clearFill: 'Clear Fill', fillHelp: 'Color format: #RRGGBB; leave blank for no fill.', verticalAlign: 'Vertical Alignment', alignCenter: 'Center' },
    pageNumber: { header: 'Header', footer: 'Footer', insert: 'Insert Page Number', style: 'Style:', position: 'Position:', left: 'Left', center: 'Center', right: 'Right', stylePage: 'Page 1', styleTotal: 'Page 1 of x', styleFirst: 'First Page', styleFirstTotal: 'First Page of X' },
    fontFamily: { SimSun: 'SimSun', SimHei: 'SimHei', KaiTi: 'KaiTi', FangSong: 'FangSong', MicrosoftYaHei: 'Microsoft YaHei', DengXian: 'DengXian', STSong: 'STSong', STHeiti: 'STHeiti', STKaiti: 'STKaiti', STFangsong: 'STFangsong', STZhongsong: 'STZhongsong', STXihei: 'STXihei', STXingkai: 'STXingkai', STLiti: 'STLiti', STXinwei: 'STXinwei', STCaiyun: 'STCaiyun' },
    fontSize: { chuhao: 'Chuhao (42 pt)', xiaochu: 'Xiaochu (36 pt)', yihao: 'Yihao (26 pt)', xiaoyi: 'Xiaoyi (24 pt)', erhao: 'Erhao (22 pt)', xiaoer: 'Xiaoer (18 pt)', sanhao: 'Sanhao (16 pt)', xiaosan: 'Xiaosan (15 pt)', sihao: 'Sihao (14 pt)', xiaosi: 'Xiaosi (12 pt)', wuhao: 'Wuhao (10.5 pt)', xiaowu: 'Xiaowu (9 pt)', liuhao: 'Liuhao (7.5 pt)', xiaoliu: 'Xiaoliu (6.5 pt)', qihao: 'Qihao (5.5 pt)', bahao: 'Bahao (5 pt)' }
  },
  comment: {
    balloon: { edit: 'Edit Comment', delete: 'Delete Comment', resolve: 'Resolve Comment', reopen: 'Reopen Comment', placeholder: 'Enter a comment...', save: 'Save', cancel: 'Cancel', source: 'From:', addReply: 'Add Reply', replyPlaceholder: 'Write a reply...', reply: 'Reply' },
    revision: { unknownAuthor: 'Unknown', accept: 'Accept Change', reject: 'Reject Change', insert: 'Inserted:', delete: 'Deleted:', format: 'Formatting:', bold: 'Bold', italic: 'Italic', underline: 'Underline', strikeout: 'Strikethrough', doubleStrikeout: 'Double Strikethrough', hidden: 'Hidden', superscript: 'Superscript', subscript: 'Subscript', color: 'Font Color', size: 'Font Size', font: 'Font', highlight: 'Highlight', characterScale: 'Character Scale', letterSpacing: 'Character Spacing', textDecoration: 'Text Decoration Style', rowFlex: 'Alignment', lineHeight: 'Line Spacing', lineHeightRule: 'Line Spacing Rule', rowMargin: 'Row Spacing', paragraphIndentLeft: 'Left Indent', paragraphIndentRight: 'Right Indent', paragraphFirstLineIndent: 'First Line Indent', indentHanging: 'Hanging Indent', paragraphSpacingBefore: 'Space Before Paragraph', paragraphSpacingAfter: 'Space After Paragraph', alignLeft: 'Align Left', alignCenter: 'Center', alignRight: 'Align Right', alignJustify: 'Justify', alignDistribute: 'Distributed', undo: 'Cancel', default: 'Default', property: '{label}: {value}', formatDescription: 'Set formatting: {details}', setFormat: 'Set Formatting', separator: ', ', descriptionSeparator: '; ' }
  }
}
