name: Sync to Gitee

on:
  schedule:
    # 每天 UTC 时间 0 点（即北京时间早上 8 点）执行一次
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许在 Actions 页面手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync code to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 引用你在 Secrets 中配置的私钥
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 【请替换】你的 GitHub 仓库地址
          source-repo: git@github.com:wanghe5201314/vervedocs.git
          # 【请替换】你的 Gitee 仓库地址
          destination-repo: git@gitee.com:wanghe520/vervedocs.git
